steps:
  - id: 'Build the container images'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME', '.']

  - id: 'Push the container image to Container Registry'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME']

  - id: 'Deploy container image to Cloud Run'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - '$_SERVICE_NAME'
    - '--image'
    - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME'
    - '--region'
    - '$_REGION'
    - '--platform'
    - 'managed'

images:
- 'gcr.io/$PROJECT_ID/$_SERVICE_NAME'

substitutions:
  _SERVICE_NAME: preview-link
  _REGION: us-west1
